BoxLayout:
                        orientation: "horizontal"
                        size_hint: 1, 0.2
                        BoxLayout:#Logs informācijai par skolēnu
                            orientation:"horizontal" #Logs informācijai par skolēnu
                            Label:
                                text: root.klase
                            Label:
                                text: "Vards\nUzvards"
                            Label:
                                text: "Pk"
                            Label:
                                text: "Dzimšanas\ndati"
                            Label:
                                text: "Telefona\nnumurs"
                            Label:
                                text: "Med\nkarte"
                            Label:
                                text: "Hroniskās\nslimības"
                        BoxLayout:
                            orientation: "vertical"
                            size_hint: 0.117, 1
                            Button:
                                text: "Rediģēt"
                            Button:
                                text: "Arhivēt"