<LoginScreen>:
    size_hint: None, None
    size: 300, 200
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}

    BoxLayout:
        spacing: 20
        padding: 20

        TextInput:
            id: username_input
            hint_text: 'Username'
            multiline: False

        TextInput:
            id: password_input
            hint_text: 'Password'
            password: True
            multiline: False

        Button:
            id: login_button
            text: 'Access'
            on_press: root.login()
